grimme-lab/mctc-lib

.github/dco.yml
.github/workflows/build.yml
.github/workflows/docs.yml
README.md

- build and deploy docs
- upload coverage reports

Add GH actions for CI

---

.github/workflows/build.yml
README.md
config/meson.build

- include Intel oneAPI compiler

Update CI workflow

---

meson.build
src/mctc/env/testing.f90
src/mctc/io.f90
src/mctc/io/read/ctfile.f90
src/mctc/io/read/vasp.f90
src/mctc/io/read/xyz.f90
src/mctc/io/structure.f90
src/mctc/io/write/ctfile.f90
src/mctc/io/write/vasp.f90
src/mctc/io/write/xyz.f90
src/mctc/version.f90
test/test_read_ctfile.f90
test/test_read_vasp.f90
test/test_read_xyz.f90

Allows to store bond topology information from connection table files (mol, sdf).

Implement bond topology in structure_type

---

.github/workflows/build.yml
CMakeLists.txt
README.md
app/CMakeLists.txt
config/CMakeLists.txt
config/template.cmake
config/template.pc
src/CMakeLists.txt
src/mctc/CMakeLists.txt
src/mctc/env/CMakeLists.txt
src/mctc/io/CMakeLists.txt
src/mctc/io/read/CMakeLists.txt
src/mctc/io/structure/CMakeLists.txt
src/mctc/io/write/CMakeLists.txt
test/CMakeLists.txt

- add CMake to CI testing as well

Implement CMake build system

---

.github/workflows/build.yml
fpm.toml

Complete the package meta data for fpm

Add meta data to fpm package manifest

---

.codecov.yml
.github/workflows/build.yml
README.md

Enable coverage report generation and upload to codecov

Add coverage analysis

---

CMakeLists.txt
fpm.toml
meson.build
src/mctc/io/structure.f90
src/mctc/io/write/vasp.f90
src/mctc/version.f90

See https://github.com/dftd4/dftd4/issues/91
Needs a release and version bump in dftd4 as well.

Allocate lattice for non-periodic structures

---

CMakeLists.txt
config/install-mod.py
config/template.pc
meson.build

See https://github.com/dftd4/dftd4/pull/95

Allow installation of module files

---

CMakeLists.txt
README.md
config/CMakeLists.txt

Try to get CMake working correctly.

Adjust CMake build files to allow usage as dependency

---

.github/workflows/build.yml
CMakeLists.txt
README.md
config/CMakeLists.txt
config/template.cmake
config/template.pc
example/CMakeLists.txt
example/meson.build
fpm.toml
meson.build
src/mctc/version.f90

Fix integrations between CMake/meson

Release version 0.2.3

---

CMakeLists.txt

Required if used as CMake subproject.

Ensure module output directory is generated in configure stage

---

.codecov.yml
.github/workflows/build.yml
docs.md
test/CMakeLists.txt

More extensive testing matrix, minor CMake updates.
Fixes #20

Update testing workflow

---

.github/workflows/build.yml
src/mctc/io/filetype.f90
src/mctc/io/read/ctfile.f90
src/mctc/io/write.f90
src/mctc/io/write/CMakeLists.txt
src/mctc/io/write/meson.build
src/mctc/io/write/qcschema.f90
src/mctc/version.f90

Following schema described in https://molssi-qc-schema.readthedocs.io/en/latest/auto_topology.html

Add support for writing QCSchema JSON

---

src/mctc/io/CMakeLists.txt
src/mctc/io/codata2018.f90
src/mctc/io/constants.f90
src/mctc/io/meson.build

Taken from https://physics.nist.gov/cuu/Constants/Table/allascii.txt

Include CODATA2018 constants

---

CMakeLists.txt

https://cmake.org/cmake/help/v3.14/command/make_directory.html

replace deprecated `make_directory` with `file(MAKE_DIRECTORY)`

---

CMakeLists.txt
fpm.toml
meson.build
src/mctc/version.F90

Please add issues which should be addressed for the next release to the 0.3.1 milestone

Release version 0.3.1

---

src/mctc/io/read/ctfile.f90
test/test_read_ctfile.f90

This adds supports for Maestro .mol files. Will close #49.

Added support for Maestro .mol files.

---

src/mctc/io/read/gaussian.f90

fix token positions

---

config/CMakeLists.txt

Add options if nvfortran is detected

---

.github/workflows/build.yml

Update versions of GH actions.

Update GH actions

---

src/mctc/ncoord.f90
test/test_data.f90
test/test_ncoord.f90

Introduces error handling for the coordination number and string translation for the available CN counting functions.

Error handling in coordination number

---

config/cmake/Findjonquil.cmake
subprojects/jonquil.wrap

Support ``null`` values in JSON input

Update jonquil to version 0.3.0
