grimme-lab/mctc-lib

fpm.toml
man/mctc-convert.1.adoc
meson.build
src/mctc/io/filetype.f90
src/mctc/io/write/xyz.f90
src/mctc/version.f90

- only write xyz in exponential notation for large numbers
- bump version to 0.1.2
- add manpage for `mctc-convert`

Allow log extension for xyz files

---

src/mctc/io/read/xyz.f90
test/test_read_xyz.f90

Support non-standard xyz input with atomic numbers instead of element symbols.
*Example*
```
24
6         -3.2624567556       -1.0740397867       -0.0000043734
7         -2.2754344008       -0.0292896574        0.0000359020
6         -0.9120851382       -0.2075386125       -0.0004880509
6         -0.3749333299        1.0720554184       -0.0001564184
7         -1.3570794708        1.9998111614        0.0003858762
6         -2.4726070186        1.3013159995        0.0005402177
1         -3.4474896946        1.7467507266        0.0010080843
7          0.9669701935        1.2880523079       -0.0003374012
6          1.8275740716        0.2107859932       -0.0000027214
8          3.0306801280        0.3524772071        0.0002192165
7          1.2570001166       -1.0570195560       -0.0000714961 …
```

Support atomic number in xyz format instead of symbols

---

app/main.f90
src/mctc/env.f90
src/mctc/env/CMakeLists.txt
src/mctc/env/meson.build
src/mctc/env/system.f90
src/mctc/io.f90
test/main.f90

- new `mctc_env_system` module (reexported in `mctc_env`)
- allow retrieving of command line arguments as deferred length characters
- allow retrieving of environment variables as deferred length characters
- simple detection logic to distinguish Unix/Windows systems

Implement system commands

---

CMakeLists.txt
app/main.f90
fpm.toml
man/mctc-convert.1.adoc
meson.build
src/mctc/io/read/pdb.f90
src/mctc/version.f90

- transfer lattice, periodicity, bonds and other annotations
- the template structure is read before the input structure from STDIN
- error if template and input structure mismatch in the number of atoms

Allow usage of template input to amend geometry information

---

doc/format-tmol.md
src/mctc/io/read/turbomole.f90
src/mctc/io/write/turbomole.f90
test/test_read_turbomole.f90

- do not backspace on unit to allow reading from stdin
- support eht group in coord format for reading of charge/uhf info

Update Turbomole reader

---

src/mctc/io/symbols.f90
test/testsuite_structure.f90

Constructor could fail due to `symbol_length` usage in the sorting step.

Don't require element symbols to match symbol_length

---

CMakeLists.txt
fpm.toml
meson.build
src/mctc/version.F90

Changelog
* Update Turbomole reader (https://github.com/grimme-lab/mctc-lib/pull/18)
* Ensure module output directory is generated in configure stage (https://github.com/grimme-lab/mctc-lib/pull/19)
* Update testing workflow (https://github.com/grimme-lab/mctc-lib/pull/21)
* Don't require element symbols to match symbol_length (https://github.com/grimme-lab/mctc-lib/pull/22)
* Add support for writing QCSchema JSON (https://github.com/grimme-lab/mctc-lib/pull/23)
* Add support for reading QCSchema JSON (https://github.com/grimme-lab/mctc-lib/pull/24)

Bump version to 0.2.4

---

README.md
src/mctc/io/read/aims.f90
src/mctc/io/read/ctfile.f90
src/mctc/io/read/gaussian.f90
src/mctc/io/read/genformat.f90
src/mctc/io/read/pdb.f90
src/mctc/io/read/turbomole.f90
src/mctc/io/read/vasp.f90
src/mctc/io/read/xyz.f90
src/mctc/io/utils.f90
test/test_read.f90
test/test_read_ctfile.f90
test/test_read_gaussian.f90
test/test_read_pdb.f90
test/test_read_turbomole.f90

Much improved error messages for users to make input errors easier to spot
```
Error: Cannot read charges
--> struc.mol:29:23-25
|
29 | M  CHG  3   1   1   3   b   2  -1
|                       ^^^ expected integer value
|
```
```
Error: Cannot read eht entry
--> struc.coord:18:13-15
|
18 | $eht charge=one unpaired=0
|             ^^^ expected integer value
|
```
```
Error: Impossible number of atoms provided
--> struc.xyz:1:1-2
|
1 | -3
| ^^ expected positive integer value
|
```

Improve error reporting for input readers

---

src/mctc/env/testing.f90

Not all tests are actually thread-safe, this enables to run the testsuite sequentially by default and on demand in parallel.
This is breaking the ABI, however since the tests are not part of the API usually exported in a shared library this is an acceptable ABI breakage and doesn't require to bump to 0.3.0 on the next release.

Make parallelization of testsuite optional

---

.github/workflows/docs.yml
src/mctc/io/read/ctfile.f90
test/test_read_ctfile.f90

Reject V3000 ctfiles, which we currently cannot parse.
Example:
```
Error: Format version not supported
--> bug566.mol:4:35-39
|
4 |   0  0  0  0  0  0  0  0  0  0999 V3000
|                                   ^^^^^ invalid format version
|
```
```
Compound 11
RDKit          3D
0  0  0  0  0  0  0  0  0  0999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 17 16 0 0 0
M  V30 BEGIN ATOM
M  V30 1 O -2.821131 -0.276238 -0.753131 0
M  V30 2 C -2.076407 0.000289 0.175864 0
M  V30 3 O -2.469860 0.872693 1.126516 0
M  V30 4 C -0.648307 -0.508439 0.384207 0 CFG=1
M  V30 5 N -0.553725 -1.908221 -0.092137 0
M  V30 6 C 0.306640 0.448659 -0.352110 0
M  V30 7 C 1.764852 0.167437 -0.097096 0
M  V30 8 C 2.575104 0.984442 0.587951 0
M  V30 9 H -3.391314 1.091514 0.873612 0
M  V30 10 H -0.438887 -0.513473 1.460318 0 …
```

Additional error handling for ctfiles in non-V2000 format

---

doc/format-gen.md
src/mctc/io/read/aims.f90
src/mctc/io/read/genformat.f90
src/mctc/io/read/turbomole.f90
src/mctc/io/utils.f90
src/mctc/io/write/aims.f90
src/mctc/io/write/genformat.f90
src/mctc/io/write/turbomole.f90
src/mctc/io/write/vasp.f90
test/test_read_aims.f90
test/test_read_genformat.f90
test/test_read_turbomole.f90

@bhourahine I have a couple of questions regarding the format
- I'm storing the helical z-axis like in DFTB+ in the first lattice vector (`shape(lattice) ==  [3, 1]`), is this the best representation?
- formats not supporting helical boundary conditions will drop the helical axis on write (similar behavior as with lattice vectors in molecular formats)
- helical boundary conditions only round-trip in gen format at the moment
- Turbomole `coord` also supports 1D periodic boundary conditions, however the periodic dimension is always given along the x-axis (`shape(lattice) ==  [3, 3]`), probably requires rotation of the coordinate system to write this in gen format
- FHI-aims `geometry.in` can define 1D periodicity as well, have to check in detail how this is supposed to work for the …

Implement support for helical boundary conditions in gen format

---

src/mctc/io/write/pdb.f90

Stale chain identifier would lead to repeated writing of `TER` after a chain changed.

Correctly update chain number when changing to another chain

---

doc/format-ctfile.md
src/mctc/io/read/ctfile.f90
test/test_read_ctfile.f90

Allow reading of v3000 connection tables

---

app/main.f90
man/mctc-convert.1.adoc

cc @hoelzerC
Allows reading `.CHRG` and `.UHF` from directory of input file (not the current working directory). 
New error message from command-line driver for invalid input.
- invalid value
```
Error: Cannot read value from file
--> ./.CHRG:1:1-2
|
1 | AB
| ^^ expected integer value
|
```
- no value
```
Error: Cannot read value from file
--> ./.CHRG:1:1
|
1 | 
| ^ expected integer value
|
```
New option to ignore `.CHRG` and `.UHF` with `--ignore-dot-files`.

Allow reading of dot-files from input file directory

---

src/mctc/io/write/turbomole.f90

For compatibility with less flexible Turbomole readers.
- write in decimal format by default, switch to scientific notation for large numbers
- don't write the `$eht` group in case the system is uncharged or has no unpaired electrons
- only write `$periodic` group for if there is at least one periodic dimension

Only write groups in Turbomole output if necessary

---

src/mctc/io/write/pdb.f90

- change from `HETATM` to `ATOM` now also updates the chain information

Update chain information when switching creating terminators in PDB

---

config/meson.build
subprojects/packagefiles/json-fortran-8.2.5/meson.build

Tested with Intel oneAPI 2022.1 and VS2022
```
cmake -B _build_intel -DCMAKE_INSTALL_PREFIX=%CD%\_dist
cmake --build _build_intel
ctest --test-dir _build_intel
cmake --build _build_intel --config Release
cmake --install _build intel
```
```
meson setup _build_intel --prefix=%CD%\_dist --default-library=static
meson compiler -C _build_intel
meson test -C _build_intel
meson install -C _build_intel
```

Allow building with Intel-CL

---

fpm.toml

Specify executable name for mctc-convert in manifest

---

config/CMakeLists.txt
meson.build

It adds the compiler ID to the include directory: include/mctc-lib/GNU-11.3.0/
This is very unconventional and unnecessary.
With this patch it now installs headers into include/mctc-lib which
aligns with the way how most projects install their headers.

Remove compiler ID from include directrory

---

src/mctc/io/write/turbomole.f90
test/test_write_turbomole.f90

At the moment, mctc-lib allows reading of coord files in angstrom format (``$coord angs``), but can not write these files. With this PR, mctc-lib will write ``$coord angs`` files if specified in the input.

Allows writing of Turbomole format with angstrom.

---

.github/workflows/build.yml

- remove old `windows` test snippets
- remove `macos-latest` tests using `intel` compiler
- more recent GNU compilers

Update CI workflow to latest state as of multicharge

---

src/mctc/io/read/vasp.f90
test/test_read_vasp.f90

Closes #60 
Closes https://github.com/dftd4/dftd4/issues/207

Add fix for reading poscar reading

---

config/CMakeLists.txt

the condition wrongly matched LLVMFlang (flang-new), which does not support `-Mbackslash` and `-Mallocatable=03`.
https://cmake.org/cmake/help/v3.24/variable/CMAKE_LANG_COMPILER_ID.html

build(cmake): fix compiler detection logic

---

src/mctc/io/read/qchem.f90
test/test_read_qchem.f90

Allows to read QChem input files specifying the geometry as z-matrix instead of cartesian coordinates.

Add QChem z-matrix reader

---

src/mctc/io/read/qchem.f90

Correctly account for atom indices for angles and dihedrals

Fix z matrix reader

---

.github/workflows/build.yml

Older versions always pull the latest fpm version, which now breaks after compiler name was added to the release artifacts (see https://github.com/fortran-lang/fpm/issues/1104).

Bump setup-fpm to v7

---

src/mctc/io/utils.f90

Fixes #63
Now prints:
```sh
[Error]: Error: coordinates not present, cannot work without coordinates
--> empty.coord:0
|
0 | 
|^ unexpected end of input
|
```

Fix error print for empty files

---

src/mctc/ncoord/type.f90

Replace reductions on arrays, which can lead to stack overflow errors for large(r) arrays. Reductions on arrays usually require increasing both `OMP_STACKSIZE` for the worker threads, but also setting `ulimit -s unlimited` to allow the stack size of the main thread to grow beyond the limit set upon starting the process. This is because reductions put the arrays on the stack, not on the heap.
We avoid this by creating private copies on the heap for each thread and add up all copies after the loop in a `critical` section, effectively emulating the reduction.

Replace OMP reductions by thread-private variables + critical

---

.gitignore
doc/format-qcschema.md
src/mctc/io/read/qcschema.F90
src/mctc/io/write/qcschema.f90
test/CMakeLists.txt
test/main.f90
test/meson.build
test/test_read_qcschema.f90
test/test_write_qcschema.f90

See https://github.com/MolSSI/QCSchema/issues/86, https://github.com/MolSSI/QCSchema/issues/66
Example:
````json
{
"schema_version": 2,
"schema_name": "qcschema_molecule",
"provenance": {
"creator": "mctc-lib",
"version": "0.4.2",
"routine": "mctc_io_write_qcschema::write_qcschema"
},
"comment": "TiO2 rutile",
"symbols": [
"Ti",
"Ti",
"O",
"O",
"O",
"O"
],
"atomic_numbers": [
22,
22,
8,
8,
8,
8
],
"geometry": [
0.0000000000000000E+00,
0.0000000000000000E+00,
0.0000000000000000E+00,
5.2818191416515159E+00,
8.2022538117381334E+00,
8.2022538117381334E+00,
6.1333938828927657E-16,
5.0082961774473045E+00,
5.0082961774473045E+00,
1.3956333869785798E-15,
1.1396211446028962E+01,
1.1396211446028962E+01,
5.2818191416515150E+00,
3.1939576342908298E+00,
1.3210549989185438E+01,
5.2818191416515150E+00, …
```

Add support for periodic boundary conditions in QCSchema IO

---

README.md
doc/format-cjson.md
doc/format-pymatgen.md
doc/format-qcschema.md
man/mctc-convert.1.adoc
src/mctc/io/filetype.f90
src/mctc/io/read.f90
src/mctc/io/read/CMakeLists.txt
src/mctc/io/read/cjson.F90
src/mctc/io/read/json.F90
src/mctc/io/read/meson.build
src/mctc/io/read/pymatgen.F90
src/mctc/io/read/qcschema.F90
src/mctc/io/write.f90
test/CMakeLists.txt
test/main.f90
test/meson.build
test/test_read_json.f90

- all JSON formats are available with `json` extension, the `read_json` procedure dispatches to the format specific readers based on the schema information in the JSON file
- update README to list all formats supported in mctc-lib

Allow for dynamically determining JSON schema of input
